### PR TITLE
Fix JS include paths and template names for profile Vue forms

### PR DESCRIPTION
**Pull request by eblount**
The include paths for these two forms need to be one directory further up, or `npm run dev` fails to run (these js files are created under the `profile` directory, unlike the standard generator). Also, the names for the Vue template tags need to not have a slash character in them or Vue fails with an error message in the console.

### CODE REVIEW

**Comment by palypster** [comment]
@eblount thank you for your PR

@matejminar please, take a look on this PR and confirm there was the bug and this PR is fixing it :)

**Comment by palypster** [comment]
Probably fixing this bug https://github.com/BRACKETS-by-TRIAD/craftable/issues/15

**Comment by matejminar** [comment]
This does not fix the https://github.com/BRACKETS-by-TRIAD/craftable/issues/15 (that was unrelated laravel-mix issue, now fixed)

I checked the PR and find out, that profile section generator works differently on windows.
If you generate profile form on OSX, you get flat profile components structure like this:

screen shot 2018-02-15 at 11 25 34

However, you got it wrapped inside 'profile' folder' on windows. That's why js paths does not work on windows. We need to inspect it further and come up with solution.

Stay tuned, or feel free to update PR.

**Comment by palypster** [comment]
Great, this looks promising. We'll have a look on it tomorrow.

**Comment by eblount** [comment]
I see. As I was on Windows, I didn't know what the js path structure _should_ have been. I'm hopeful that my update will solve the issue on all platforms. I have tested on Windows, and the change to the str_replace fixes the issue, making the directory structure like your screenshot.

**Comment by matejminar** [comment]
Great, thank you. We have tested it both on Windows and OSX and it works like a charm!

**Comment by davidhunt018** [comment]
Hello,

I hope you are doing great.

Please i installed the project in windows 10 but after installation and database migration, i have a layout problem (don't load css and js scripts)

from web browser consol i see that the css files load from bad path (ex:  http://localhost/js/admin.js)

I atteched screenshots in attached.

Please Help

error 2
error

**Comment by palypster** [comment]
`npm install && npm run dev` ?

**Comment by davidhunt018** [comment]
Yes i did that not working.

When I change the css path manually in the browser consol, it loads the layout.

I notice that I'm using Xampp server in local on windows 10

Need advise please. I'm stacked in this step days ago

Thank you brothers.

**Comment by palypster** [comment]
From the sceenshot you have provided the problem is you have misconfigured your web server. You should not have URL likes this:

http://localhost/something/public/admin

but rather like this:

http://localhost/admin

One workaround would be to set up correct base URL via `<base>` html tag (but that will "fix" only you development and break you production env, most likely, so I recommend you to properly configure you web server).

**Pull request merged**
